// components/sponsorsList.vue
<template>
    <section class="py-32 bg-white" data-header-text="text-gray-dark">
        <div class="container inner">
            <div>
                <div class="flex items-center justify-center">
                    <img class="md:w-122 w-55 mr-20" src="/img/googlelogo.png" alt="Google sponsor logo" />
                    <img class="md:w-122 w-55 mr-20" src="/img/linuxfoundationlogo.png" alt="Linux Foundation sponsor logo" />
                    <img class="md:w-122 w-55 md:mr-20" src="/img/chainguard.svg" alt="Chainguard sponsor logo" />
                    <img class="md:w-122 w-55 mr-20" src="/img/redhatlogo.png" alt="RedHat sponsor logo" />
                    <img class="md:w-122 w-55 mr-20" src="/img/purdueunilogo.png" alt="Purdue University sponsor logo" />
                    <img class="md:w-122 w-55 mr-20" src="/img/stacklok.png" alt="Stacklok sponsor logo" />
                </div>
            </div>
        </div>
    </section>
</template>
<script lang="js">
// import LinkButton from "@/assets/icons/link.svg";
export default {

    components: {
        // LinkButton
    },

    data: () => ({
        articlesArray: {
            type: Array,
            default: null
        }
    }),

    computed: {
    },

    created() {
    },

    methods: {
    },

};
</script>

// src/components/sections/SponsorsList.tsx
export function SponsorsList() {
  return (
    <section className="py-32 bg-white" data-header-text="text-gray-dark">
      <div className="container inner">
        <div className="flex items-center justify-center">
          <img className="md:w-122 w-55 mr-20" src="/img/googlelogo.png" alt="Google sponsor logo" />
          <img className="md:w-122 w-55 mr-20" src="/img/linuxfoundationlogo.png" alt="Linux Foundation sponsor logo" />
          <img className="md:w-122 w-55 md:mr-20" src="/img/chainguard.svg" alt="Chainguard sponsor logo" />
          <img className="md:w-122 w-55 mr-20" src="/img/redhatlogo.png" alt="RedHat sponsor logo" />
          <img className="md:w-122 w-55 mr-20" src="/img/purdueunilogo.png" alt="Purdue University sponsor logo" />
          <img className="md:w-122 w-55 mr-20" src="/img/stacklok.png" alt="Stacklok sponsor logo" />
        </div>
      </div>
    </section>
  );
}
