// components/twoColumnTextGrid.vue
<template>
    <section class="py-64 md:py-0 md:px-16" :class="[$route.params.slug === 'trust-security' ? 'bg-purple-dark' : 'bg-white']" data-header-text="text-gray-dark">
        <div class="container">
            <div class="md:max-w-1/2 w-full">
                <h3 v-animate-on-scroll class="pb-64 delay-step_1" :class="[$route.params.slug === 'community' ? 'text-orange-dark' : 'text-purple-dark']">{{ header }}</h3>
                <div v-if="text" v-animate-on-scroll class="delay-step_3 pb-64 text-gray-dark" v-html="$md.render(text)"></div>
            </div>
            <h3 v-if="subHeader" class="pb-64 text-white text-center flex-none block w-full">{{ subHeader }}</h3>
            <div class="md:flex items-start md:-ml-30 md:-mr-30 md:pr-30" :class="[column2.header ? 'justify-between':'justify-start']">
                <Card v-bind="column1" />
                <Card v-bind="column2" />
            </div>
        </div>
    </section>
</template>
<script lang="js">
import Card from '@/components/Card.vue';
export default {

    components: {
        Card
    },

    props: {
        column1: {
            type: Object,
            default: null
        },
        column2: {
            type: Object,
            default: null
        },
    },

    data: () => ({
    }),

    computed: {
        backgroundColour(){
            return `background: ${this.bgColour};`;
        }
    },

    mounted() {
    },

    methods: {
    }

};
</script>

// src/components/sections/TwoColumnTextGrid.tsx
"use client";

import { useAnimateOnScroll } from "@/hooks/useAnimateOnScroll";
import { MarkdownRenderer } from "@/components/ui/MarkdownRenderer";
import { Card } from "@/components/sections/Card";

interface ColumnData {
  header?: string;
  subHeader?: string;
  text?: string;
  imageAsset?: string;
  bgColour?: string;
  ctaLink?: string;
  ctaText?: string;
  isCardStyle?: boolean;
  [key: string]: unknown;
}

interface TwoColumnTextGridProps {
  header?: string;
  subHeader?: string;
  text?: string;
  column1?: ColumnData;
  column2?: ColumnData;
  slug?: string;
}

export function TwoColumnTextGrid({
  header,
  subHeader,
  text,
  column1,
  column2,
  slug,
}: TwoColumnTextGridProps) {
  const animRef1 = useAnimateOnScroll();
  const animRef2 = useAnimateOnScroll();

  const isTrustSecurity = slug === "trust-security";
  const isCommunity = slug === "community";

  return (
    <section
      className={`py-64 md:py-0 md:px-16 ${
        isTrustSecurity ? "bg-purple-dark" : "bg-white"
      }`}
      data-header-text="text-gray-dark"
    >
      <div className="container">
        <div className="md:max-w-[50%] w-full">
          {header && (
            <h3
              ref={animRef1}
              className={`pb-64 delay-step_1 ${
                isCommunity ? "text-orange-dark" : "text-purple-dark"
              }`}
            >
              {header}
            </h3>
          )}
          {text && (
            <div ref={animRef2} className="delay-step_3 pb-64 text-gray-dark">
              <MarkdownRenderer content={text} />
            </div>
          )}
        </div>
        {subHeader && (
          <h3 className="pb-64 text-white text-center flex-none block w-full">
            {subHeader}
          </h3>
        )}
        <div
          className={`md:flex items-start md:-ml-30 md:-mr-30 md:pr-30 ${
            column2?.header ? "justify-between" : "justify-start"
          }`}
        >
          {column1 && <Card {...column1} slug={slug} />}
          {column2 && <Card {...column2} slug={slug} />}
        </div>
      </div>
    </section>
  );
}
