// src/components/sections/TwoColumnAnnouncement.tsx
import { MarkdownRenderer } from "@/components/ui/MarkdownRenderer";

interface TwoColumnAnnouncementProps {
  header?: string;
  text?: string;
  imageAsset?: string;
  alignment?: string;
  bgColour?: string;
  card?: Record<string, unknown>;
  link?: string;
  slug?: string;
}

function headerTextClass(bgColour?: string): string {
  if (bgColour === "bg-purple-dark") return "text-white";
  if (bgColour === "bg-pastel-blue") return "text-purple-dark";
  return "text-gray-dark";
}

export function TwoColumnAnnouncement({
  header,
  text,
  imageAsset,
  alignment,
  bgColour,
  card,
  link,
}: TwoColumnAnnouncementProps) {
  const isTextRight = alignment === "textRight";

  return (
    <section
      className={`py-40 md:py-80 ${bgColour || ""}`}
      data-header-text={headerTextClass(bgColour)}
    >
      <div
        className={`md:flex justify-between container inner ${
          !isTextRight ? "items-center" : "items-start"
        }`}
      >
        <div className="w-full md:w-1/2 delay-step_1 md:mr-80 md:order-1 order-2">
          <h1 className="text-24 leading-23 md:leading-32 mb-32 text-purple-dark">
            {header}
          </h1>
          {!isTextRight && text && (
            <div className="mt-8 md:block hidden text-purple-dark">
              <MarkdownRenderer content={text} />
            </div>
          )}
          {!isTextRight && imageAsset && (
            <div className="block md:hidden">
              <a href={link}>
                <img alt={`${header} image`} src={imageAsset} />
              </a>
            </div>
          )}
        </div>
        {!card && (
          <div className="w-full md:w-1/2 delay-step_2 mt-32 md:mt-0 md:order-2">
            {!isTextRight && imageAsset && (
              <div className="md:block hidden">
                <a href={link}>
                  <img alt={`${header} image`} src={imageAsset} />
                </a>
              </div>
            )}
            {isTextRight && text && (
              <MarkdownRenderer content={text} />
            )}
            {!isTextRight && text && (
              <div className="mt-8 block md:hidden text-purple-dark">
                <MarkdownRenderer content={text} />
              </div>
            )}
          </div>
        )}
      </div>
    </section>
  );
}

// components/twoColumnAnnouncement.vue
<template>
    <section class="py-40 md:py-80" 
    :class="[backgroundColour]" 
    :data-header-text="[(backgroundColour === 'bg-purple-dark') ? 'text-white' : (backgroundColour === 'bg-pastel-blue') ? 'text-purple-dark' : 'text-gray-dark']"
    >
        <div class="md:flex justify-between container inner" :class="[textAlignment != 'textRight' ? 'items-center' : 'items-start']">
            <div class="w-full md:w-1/2 step-delay_1 md:mr-80 md:order-1 order-2">
                <h1 class="text-24 leading-23 md:leading-32 mb-32" :class="[!bgColour ? 'text-purple-dark' : 'text-purple-dark']">{{header}}</h1>
                <div v-if="textAlignment != 'textRight'" :class="[!bgColour ? 'text-purple-dark' : 'text-purple-dark']" class="mt-8 md:block hidden" v-html="$md.render(text)"></div>
                <div v-if="textAlignment != 'textRight'" class="block md:hidden"><a :href="link"><img :alt="`${header} image`" :src="imageAsset" /></a></div>
            </div>
            <div v-if="!card" class="w-full md:w-1/2 step-delay_2 mt-32 md:mt-0 md:order-2">
                <div v-if="textAlignment != 'textRight'" class="md:block hidden"><a :href="link"><img :alt="`${header} image`" :src="imageAsset" /></a></div>
            </div>
                <div v-else v-html="$md.render(text)"></div>
                <div v-if="textAlignment != 'textRight'" :class="[!bgColour ? 'text-purple-dark' : 'text-white']" class="mt-8 block md:hidden" v-html="$md.render(text)"></div>
            </div>
        </div>
    </section>
</template>
<script lang="js">
export default {

    components: {

    },

    props: {
        header: { type: String, default: null },
        text: { type: String, default: null },
        imageAsset: { type: String, default: null },
        alignment: { type: String, default: null },
        bgColour: { type: String, default: null },
        card: { type: Object, default: null },
        link: { type: String, default: null },
    },

    data: () => ({
    }),

    computed: {
        backgroundColour(){
            return `${this.bgColour}`;
        },
        textAlignment() {
            return this.alignment;
        },
    },

    mounted() {
    },

    methods: {
    }

};
</script>
